quality: 7
valence: 1
intensity: 7
Acousticness: 0.322
Album Image URL: https://i.scdn.co/image/ab67616d0000b273c6e0948bbb0681ff29cdbae8
Album Name: 2014 Forest Hills Drive
Album Release Date: '2014-12-09'
Album URI: spotify:album:0UMMIkurRUmkruZ3KGBLtG
Artist Genres:
- conscious hip hop
- hip hop
- north carolina hip hop
- rap
Artist URI(s): spotify:artist:6l3HvQ5sa6mXTsMTB19rO5
Danceability: 0.889
Energy: 0.4
Explicit: 'true'
Instrumentalness: 1.32e-05
Key: 4.0
Label: Roc Nation Records LLC
Liveness: 0.331
Loudness: -10.586
Mode: 0.0
Popularity: 74.0
Speechiness: 0.26
Tempo: 128.073
Time Signature: 4.0
Track Duration (ms): 301064.0
Track Number: 8.0
Valence: 0.336
